/**
 * ISS rate seeds from verified non-capital sources — federal NFSe alíquotas + municipal legislation.
 *
 * 134 rows: gov.br NFS-e national platform alíquotas table (all 5,571 municipalities,
 * extraction 2026-09-03, updated 2026-09-16), restricted to municipalities with >= 100
 * currently-valid service rows so the min/max band is representative. Bands were adopted
 * as registered (all within the LC 116 Art. 8 2%–5% band).
 * @see https://www.gov.br/nfse/pt-br/biblioteca/aliquotas
 *
 * 3 rows: municipal legislation verified directly (absent from the NFSe table):
 * - Campinas/SP — Lei 12.392/2005, Art. 27 (2%–5%), via Biblioteca Jurídica da Prefeitura.
 * - Niterói/RJ — Lei 2.597/2008 arts. 65–124 (2%, 3%, 5%), via Secretaria Municipal de Fazenda.
 * - Barueri/SP — CTM LC 118/2002 + LC 157/2016 service table (2%–5%), via Secretaria de Finanças
 *   Lista de Serviços com Códigos e Alíquotas.
 *
 * Rows below the 100-service threshold (e.g. Olímpia/SP, Quissamã/RJ) stay estimativa-only.
 * @see https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm#art8
 */

import type { IssMunicipalRateSeed } from './iss-municipal-capital-seeds.js';

export const ISS_MUNICIPAL_NFSE_URL =
  'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas';

export const ISS_MUNICIPAL_NFSE_SEEDS: readonly IssMunicipalRateSeed[] = [
  { codigoIbge: 3300209, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3300233, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3300258, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3300308, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3300407, aliquotaMin: 4, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3300456, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3300704, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3301306, aliquotaMin: 5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3301702, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3301900, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3302205, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3302254, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3302502, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3302700, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3302858, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3303203, aliquotaMin: 2.5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3303302, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.fazenda.niteroi.rj.gov.br/site/iss' },
  { codigoIbge: 3303401, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3303500, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3303807, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3303906, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3304110, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3304144, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3304201, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3304904, aliquotaMin: 5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3305000, aliquotaMin: 2.5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3305109, aliquotaMin: 2.5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3305208, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3305554, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3305802, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3306008, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3306107, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3306305, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3501152, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3501608, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3501905, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3502101, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3502754, aliquotaMin: 5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3502804, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3503208, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3503307, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3503901, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3504008, aliquotaMin: 3.5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3504107, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3504503, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3505708, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://portal.barueri.sp.gov.br/secretarias/secretaria-de-financas/lista-de-servicos-com-codigos-e-aliquotas-pessoa-juridica-e-fisica' },
  { codigoIbge: 3506003, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3506102, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3506508, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3507001, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3507506, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3507605, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3508405, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3508504, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3509007, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3509205, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3509502, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://bibliotecajuridica.campinas.sp.gov.br/index/visualizaratualizada/id/85556' },
  { codigoIbge: 3509601, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3510500, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3510609, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3511102, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3512407, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3513009, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3513405, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3513504, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3515004, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3515707, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3516200, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3516408, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3517406, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3518404, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3518701, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3519071, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3520400, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3520509, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3522208, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3522307, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3522406, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3522505, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3522604, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3523107, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3523404, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3524006, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3524402, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3524709, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3525003, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3525201, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3525300, aliquotaMin: 2.5, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3526704, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3526803, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3526902, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3527108, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3527207, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3527306, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3529005, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3530300, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3530508, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3530607, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3530706, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3530805, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3531308, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3531803, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3533403, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3534302, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3534401, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3534708, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3536703, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3538006, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3538709, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3539301, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3539806, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3540606, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3541406, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3541604, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3543402, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3545209, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3545803, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3546405, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3546702, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3547304, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3548906, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3549102, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3549805, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3550605, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3550704, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3551009, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3551702, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3552403, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3552809, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3554003, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3554102, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3556206, aliquotaMin: 3, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3556453, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3556503, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3556701, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3557006, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
  { codigoIbge: 3557105, aliquotaMin: 2, aliquotaMax: 5, leiUrl: 'https://www.gov.br/nfse/pt-br/biblioteca/aliquotas' },
];
